### ISSUE TITLE
function getSignificance cannot run correctly

### ISSUE THREAD

**Issue by zedeel** [lijxug/CSOmapR#1]
> Consider replacing `is.matrix` to `coordinates` here.

```R
if(ncol(is.matrix) < 2 | ncol(is.matrix) > 3)
  warning("Abnormal number of dimensions of the coordinates")
```

> `logging` package should be imported when setting `verbose = T`.

Otherwise, `loginfo` function cannot run correctly.

```R
if(verbose) loginfo("identify topK")
```

**Comment by lijxug** [comment]
Thank you for the kind suggestions.
