### ISSUE TITLE
How to transform UMI count to TPM

### ISSUE THREAD

**Issue by HIT-ImmunologyLab** [lijxug/CSOmapR#3]
For 10x single-cell transcriptome expression value (UMI count), how to transform the UMI count to TPM value?

**Comment by Japrin** [comment]
It is enough to normalize the expression value using a size factor (e.g. dividing the UMI of each gene by the total UMI count of the cell then scaling  by 1e4).

**Comment by lijxug** [comment]
Thanks, Japrin.
