### ISSUE TITLE
Cannot intstall CSOmapR?

### ISSUE THREAD

**Issue by aaronwolf1995** [lijxug/CSOmapR#5]
Hi! I have installed Rtools, and:
devtools::install_github("lijxug/CSOmapR.demo")
is OK to run.
But when I tried to install CSOmapR, there appears an error:
![image](https://user-images.githubusercontent.com/63252705/108736057-30c3fb00-756c-11eb-9ecd-8920dbac71e4.png)
Could you give me some clues for installing?
Thanks!

**Comment by lijxug** [comment]
Yeah... about that. 
 CSOmapR is only available on the linux-based machines now.

**Comment by aaronwolf1995** [comment]
Ok, thanks. I have ubuntu based WSL subsystem and online service as well, I will have a try.
