### ISSUE TITLE
enrichment or depletion？

### ISSUE THREAD

**Issue by xxbb23** [lijxug/CSOmapR#9]
Hi!
I have a problem：
Could you please tell me how to infer enrichment or depletion through the results generated by getSignificance?
It has two P values.Confuse me.
Thanks!

**Comment by lijxug** [comment]
Sorry for the inconvenient.  The result of `getSignificance` contains a qvalue matrix and a pvalue matrix. Both of them indicates the enrichment. You can achieve the p-values for depletion simply by calculating `1 - pvalue`, then adjust it accordingly.

**Comment by xxbb23** [comment]
Thank you
